# -*- coding: utf-8 -*-
"""Copy of expensetracker.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c2doxuOKUqyGl4l8HPTlydf5XxAi5ZIW
"""

import matplotlib.pyplot as plt
import numpy as np
expenses = []
while True:
    print("\nEXPENSE TRACKER")
    print("1. Add new expense")
    print("2. View all expenses")
    print("3. Exit")
    choice = input("Choose option (1,2,3): ")
    if choice == "1":
        print("\n--- Add a new expense ---")
        date = input("Date:")
        amount = int(input("Amount(₹):"))
        category = input("Category (Food, Travel, Shopping, etc.): ")
        expense = date + "," + str(amount) + "," + category
        expenses.append(expense)
        print("Expense added successfully\n")
    elif choice == "2":
        print("\n--- Your Expenses ---")
        if len(expenses) == 0:
            print("No expenses added.\n")
        else:
            print("Date     | Amount | Category")
            total = 0
            for expense in expenses:
                parts = expense.split(",")
                date = parts[0]
                amount = parts[1]
                category = parts[2]
                print(date, " | ₹" + amount, " |", category)
                total += int(amount)
            print("Total Expenses = ₹" + str(total) + "\n")
            amounts = []
            for expense in expenses:
                parts = expense.split(",")
                amounts.append(int(parts[1]))
            arr = np.array(amounts)
            print(f"Average expenses is {np.mean(arr):.2f}")
            labels = [expense.split(',')[2] for expense in expenses]
            sizes = [int(expense.split(',')[1]) for expense in expenses]
            plt.pie(sizes, labels=labels, autopct='%1.1f%%', startangle=90)
            plt.show()
    elif choice == "3":
        print("Exiting")
        break
    else:
        print("Invalid choice. Try again.")